Repository Exodus-Privacy/exodus-android-app, pull requests merged in 2022-07, with the labels that each got.

#179 fix: add no internet Snackbar and fix crash #178
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/ExodusUpdateService.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivity.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivityViewModel.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps/AppsFragment.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackers/TrackersFragment.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/network/NetworkManager.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/NotificationManagerModule.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, rewrite

#182 app: Improve date support
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/ExodusUpdateService.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailFragment.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailViewModel.kt
  app/src/main/res/layout/fragment_app_detail.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: rewrite

#183 Show all permissions on ADPermissionsFragment
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/model/ADPermissionsRVAdapter.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/PackageManagerModule.kt
Labels: rewrite

#184 app: Add new text when 2 versionName is same on AppDetailFragment
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailFragment.kt
  app/src/main/res/layout/fragment_app_detail.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, rewrite

#180 Improve workflows
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: enhancement

#187 app: Fix tracker chip
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/CommonExtensions.kt
  app/src/main/res/layout/fragment_a_d_trackers.xml
  app/src/main/res/layout/fragment_app_detail.xml
  app/src/main/res/layout/recycler_view_app_item.xml
Labels: enhancement, rewrite

#188 Add new Dialog Fragment to select Theme
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/about/AboutFragment.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/dialog/ThemeDialogFragment.kt
  app/src/main/res/menu/about_menu.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, rewrite

#189 fix: minSDK 21 - aa0da6ce27b2b142a1e3f21fc657972dbd321285
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/ExodusUpdateService.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/network/NetworkManager.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/NotificationManagerModule.kt
  app/src/main/res/layout/fragment_about.xml
Labels: bug
