Repository Exodus-Privacy/exodus-android-app, pull requests merged in 2022-08, with the labels that each got.

#193 Improved apps, trackers and permissions sorting
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/database/app/ExodusApplicationDao.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/database/tracker/TrackerDataDao.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/PackageManagerModule.kt
Labels: enhancement, rewrite

#195 Relecture des versions anglaise et française
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: rewrite

#192 Fix null show on permissions without label and description
  app/build.gradle
  app/src/androidTest/java/org/eu/exodus_privacy/exodusprivacy/BaseTest.kt
  app/src/androidTest/java/org/eu/exodus_privacy/exodusprivacy/ExampleInstrumentedTest.java
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/model/ADPermissionsRVAdapter.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/PackageManagerModule.kt
Labels: bug, rewrite

#190 Improved format
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/ExodusUpdateService.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/about/AboutFragment.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailFragment.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/dialog/ThemeDialogFragment.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/database/ExodusDatabase.kt
  app/src/main/java/org/eu/exodus_privacy/exodusprivacy/utils/PackageManagerModule.kt
  app/src/main/res/anim/slide_in_bottom.xml
  app/src/main/res/anim/slide_in_left.xml
  app/src/main/res/anim/slide_in_right.xml
  app/src/main/res/anim/slide_in_top.xml
  app/src/main/res/anim/slide_out_left.xml
  app/src/main/res/anim/slide_out_right.xml
  app/src/main/res/drawable/ic_android.xml
  app/src/main/res/drawable/ic_apps.xml
  app/src/main/res/drawable/ic_apps_filled.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_baseline_filter_list_24.xml
  app/src/main/res/drawable/ic_danger.xml
  app/src/main/res/drawable/ic_forward.xml
  app/src/main/res/drawable/ic_information_filled.xml
  app/src/main/res/drawable/ic_match.xml
  app/src/main/res/drawable/ic_mismatch.xml
  app/src/main/res/drawable/ic_open.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_tracker.xml
  app/src/main/res/drawable/ic_tracker_filled.xml
  app/src/main/res/drawable/ic_unavailable.xml
  app/src/main/res/drawable/navbar_app.xml
  app/src/main/res/drawable/navbar_information.xml
  app/src/main/res/drawable/navbar_tracker.xml
  app/src/main/res/drawable/percent.xml
  app/src/main/res/drawable/progressbar.xml
  app/src/main/res/drawable/square_dark_orange.xml
  app/src/main/res/drawable/square_light_blue.xml
  app/src/main/res/drawable/square_light_red.xml
  app/src/main/res/drawable/square_light_yellow.xml
  app/src/main/res/drawable/square_purple.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/layout/fragment_app_detail.xml
  app/src/main/res/layout/fragment_apps.xml
  app/src/main/res/layout/fragment_tracker_detail.xml
  app/src/main/res/menu/about_menu.xml
  app/src/main/res/menu/apps_menu.xml
  app/src/main/res/menu/popup_menu_filter.xml
  app/src/main/res/navigation/navigation_resource.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, rewrite

#160 Turkish Translation
  app/src/main/res/values-tr/strings.xml
  fastlane/metadata/android/tr/full_description.txt
  fastlane/metadata/android/tr/short_description.txt
Labels: enhancement

#199 release 3.0.0
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/13.txt
  fastlane/metadata/android/en-US/images/phoneScreenshots/app_list.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/report1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/report2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/report2_2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/tracker1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/tracker2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/tracker2_2.png
  fastlane/metadata/android/fr-FR/changelogs/13.txt
  fastlane/metadata/android/fr-FR/images/phoneScreenshots/app_list.png
  fastlane/metadata/android/fr-FR/images/phoneScreenshots/report1.png
  fastlane/metadata/android/fr-FR/images/phoneScreenshots/report2.png
  fastlane/metadata/android/fr-FR/images/phoneScreenshots/report2_2.png
  fastlane/metadata/android/fr-FR/images/phoneScreenshots/tracker1.png
  fastlane/metadata/android/fr-FR/images/phoneScreenshots/tracker2.png
  fastlane/metadata/android/fr-FR/images/phoneScreenshots/tracker2_2.png
Labels: release

#200 Reports and trackers are never download
  .github/workflows/release.yml
  app/build.gradle
Labels: bug
